# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-25 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170224_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='track_file',
        ),
    ]
